package com.health.companion.data.remote.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import retrofit2.http.GET

interface FilesApi {

    /** Returns all files generated by the AI agent for the current user. */
    @GET("files/generated")
    suspend fun listGeneratedFiles(): List<GeneratedFileInfo>
}

@Serializable
data class GeneratedFileInfo(
    val filename: String,
    @SerialName("conversation_id") val conversationId: String = "",
    @SerialName("size_kb") val sizeKb: Float = 0f,
    @SerialName("download_url") val downloadUrl: String = "",
    // Legacy field — kept for backwards compat
    val url: String = "",
    @SerialName("mime_type") val mimeType: String = "application/octet-stream"
) {
    /** Returns whichever URL field is populated. */
    val resolvedUrl: String get() = downloadUrl.ifBlank { url }
}
